function details(productId, productNameKor, productNameEng, price, sugarContent, body, kind, regionName, winery, vintage, alcohol, grapeKind, totalQuantity) {

var String = '<div class="product-images">'
           + '  <div class="main-image images">'
           + '    <img alt="big images" src="' + Utils.getImagePath(productId) + '">'
           + '  </div>'
           + '</div>'
           + '<div class="product-info">'
           + '  <input type="hidden" id="productId" value='+ productId +'>'
           + '  <h1>'+ productNameKor +'</h1>'
           + '  <h3>'+ productNameEng +'</h3>'
           + '  <div class="rating__and__review">'
           + '    <ul class="rating">'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '    </ul>'
           + '    <div class="review">'
           + '      <a href="components/item/review.html" id="productReview">구매후기</a>'
           + '    </div>'
           + '  </div>'
           + '  <div class="price-box-3">'
           + '    <div class="s-price-box">'
           + '      <span class="new-price">'+ Number(price).toLocaleString('en') + '원' +'</span>'
           + '    </div>'
           + '  </div>'
           + '  <div class="product_details">'
  	       + '    <div class="quick-desc">'
           + '      상품설명'
           + '    </div>'
           + '    <div>'
           + '      <ul>'
           + '        <li>당도 : '+ sugarContent +'</li>'
           + '        <li>바디 : '+ body +'</li>'
           + '        <li>종류 : '+ kind +'</li>'
           + '        <li>생산국가 : '+ regionName +'</li>'
           + '        <li>와이너리 : '+ winery +'</li>'
           + '        <li>빈티지 : '+ vintage +'</li>'
           + '        <li>알코올도수 : '+ alcohol +'</li>'
           + '        <li>포도품종 : '+ grapeKind +'</li>'
           + '      </ul>'
           + '    </div>'
           + '    <div>'
           + '      수량 :' 
           + '      <input type="number" id="quantity" step="1" value="1" min="1" max="' + totalQuantity + '">'
           + '    </div>'
           + '  </div>'
           + '  <div class="addtocart-btn">'
           + '    <a href="components/cart.html" id="goToPurchase">구매하기</a>'
           + '    <a href="#" style="float: right;">장바구니 담기</a>'
           + '  </div>'
           + '</div>';

$('.modal-product').append(String);
}