function details(alcohol, sugarContent, grapeKind, productId, kind, regionName, productNameEng, body, totalQuantity, vintage, price, winery, productNameKor) {

var String = '<div class="product-images">'
           + '  <div class="main-image images">'
           + '    <img alt="big images" src="images/product/big-img/Wine.jpg">'
           + '  </div>'
           + '</div>'
           + '<div class="product-info">'
           + '  <h1>상품이름</h1>'
           + '  <div class="rating__and__review">'
           + '    <ul class="rating">'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '      <li><span class="ti-star"></span></li>'
           + '    </ul>'
           + '    <div class="review">'
           + '      <a href="components/item/review.html" id="productReview">구매후기</a>'
           + '    </div>'
           + '  </div>'
           + '  <div class="price-box-3">'
           + '    <div class="s-price-box">'
           + '      <span class="new-price">상품가격</span>'
           + '    </div>'
           + '  </div>'
           + '  <div class="product_details">'
  	       + '    <div class="quick-desc">'
           + '      상품설명'
           + '    </div>'
           + '    <div>'
           + '      <ul>'
           + '        <li>당도</li>'
           + '        <li>바디</li>'
           + '        <li>종류</li>'
           + '        <li>생산국가</li>'
           + '        <li>와이너리</li>'
           + '        <li>생산자</li>'
           + '        <li>빈티지</li>'
           + '        <li>알코올도수</li>'
           + '        <li>포도품종</li>'
           + '      </ul>'
           + '    </div>'
           + '  </div>'
           + '  <div class="addtocart-btn">'
           + '    <a href="cart.html">구매하기</a>'
           + '    <a href="#" style="float: right;">장바구니 담기</a>'
           + '  </div>'
           + '</div>';

$('#product').append(String);
}