function write(category, title, content, regdate) {
	var String = '<h4>게시글 상세보기</h4>'
	           + '<div class="input-group">'
	           + '  <table class="table table-striped table-bordered">'
	           + '    <thead>'
	           + '      <tr>'
	           + '        <th>글 제목</th>'
	           + '        <td colspan="3"><input type="text" name="subject" class="form-control" value=""></td>'
	           + '      </tr>'
	           + '      <tr>'
	           + '        <th>작성자</th>'
	           + '        <td><input type="text" name="writer" class="form-control" value=""></td>'
	           + '        <th>작성일</th>'
	           + '        <td><input type="text" name="regdate" class="form-control" value=""></td>'
	           + '      </tr>'
	           + '      <tr>'
	           + '        <th>아이피</th>'
	           + '        <td><input type="text" name="ip" class="form-control"></td>'
	           + '        <th>조회수</th>'
	           + '        <td><input type="text" name="hitcount" class="form-control" value=""></td>'
	           + '      </tr>'
	           + '    </thead>'
	           + '    <tbody>'
	           + '      <tr>'
	           + '        <td colspan="4">'
	           + '          <textarea class="form-control" rows="15" name="content"></textarea>'
	           + '        </td>'
	           + '      </tr>'
	           + '    </tbody>'
	           + '  </table>'
	           + '</div>';
	
	$('.col-md-12').append(String);
}